[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[target.x86_64-pc-windows-gnu]
#linker="lld"
rustflags = ["-Zshare-generics=off"]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"